# Generated by Django 2.2.11 on 2021-05-06 18:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0034_auto_20201122_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('file_url', models.URLField()),
                ('name', models.CharField(default='', max_length=1024)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('WORKING', 'WORKING'), ('FAILED', 'FAILED'), ('STOPPED', 'STOPPED')], default='PENDING', max_length=100)),
                ('next_runtime', models.DateTimeField(auto_now_add=True)),
                ('periodicity', models.IntegerField(default=10)),
                ('contact_email', models.EmailField(max_length=254)),
                ('last_errors', models.TextField(blank=True, null=True)),
                ('suppress_emails', models.BooleanField(default=False)),
                ('email_periodicity', models.IntegerField(default=10)),
                ('email_next_sendtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LifeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('data_id', models.CharField(db_index=True, max_length=1024)),
                ('category', models.CharField(db_index=True, default='', max_length=1024)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('phone_1', models.CharField(max_length=200)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('downvotes', models.IntegerField(default=0)),
                ('upvotes', models.IntegerField(default=0)),
                ('created_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Job')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.District')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.State')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
