# Generated by Django 2.2.11 on 2020-03-21 20:35

import life.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20200321_2029"),
    ]

    operations = []
